'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PostOpRep.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _946378_196640293851376_265703448_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_946378_196640293851376_265703448_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property e_mail1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("e_mail1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm that you wish to submit the Debrief report? An E-mail will be sent to the Unit Management Team and all members in attendance..
        '''</summary>
        Friend ReadOnly Property EmailConfirmation() As String
            Get
                Return ResourceManager.GetString("EmailConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit Debrief.
        '''</summary>
        Friend ReadOnly Property EmailConfirmationTitle() As String
            Get
                Return ResourceManager.GetString("EmailConfirmationTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The SMTP Host Name provided is either not valid, or a connection to the server is unable to be established. Would you like to restore the original settings?.
        '''</summary>
        Friend ReadOnly Property Invalid_SMTP_Host_Provided() As String
            Get
                Return ResourceManager.GetString("Invalid_SMTP_Host_Provided", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed Connection to SMTP Host Server.
        '''</summary>
        Friend ReadOnly Property Invalid_SMTP_Message_Title() As String
            Get
                Return ResourceManager.GetString("Invalid_SMTP_Message_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not a valid E-mail address..
        '''</summary>
        Friend ReadOnly Property InvalidEmailAddress() As String
            Get
                Return ResourceManager.GetString("InvalidEmailAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} does not exist. Please contact administrator..
        '''</summary>
        Friend ReadOnly Property LoginLoginIncorrect() As String
            Get
                Return ResourceManager.GetString("LoginLoginIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorrect password. If password reset is required, then please contact administrator..
        '''</summary>
        Friend ReadOnly Property LoginPasswordIncorrect() As String
            Get
                Return ResourceManager.GetString("LoginPasswordIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The ID {0} has already been assigned to another member. Please re-enter a different ID..
        '''</summary>
        Friend ReadOnly Property NewMemberIDAlreadyExists() As String
            Get
                Return ResourceManager.GetString("NewMemberIDAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Member ID Already Exists.
        '''</summary>
        Friend ReadOnly Property NewMemberIDAlreadyExistsTitle() As String
            Get
                Return ResourceManager.GetString("NewMemberIDAlreadyExistsTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ses00050.
        '''</summary>
        Friend ReadOnly Property PermissionControllerID() As String
            Get
                Return ResourceManager.GetString("PermissionControllerID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ses00051.
        '''</summary>
        Friend ReadOnly Property PermissionDeputyControllerID() As String
            Get
                Return ResourceManager.GetString("PermissionDeputyControllerID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ses00054.
        '''</summary>
        Friend ReadOnly Property PermissionDeputyTeamLeaderID() As String
            Get
                Return ResourceManager.GetString("PermissionDeputyTeamLeaderID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ses00052.
        '''</summary>
        Friend ReadOnly Property PermissionSectionLeaderID() As String
            Get
                Return ResourceManager.GetString("PermissionSectionLeaderID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;member&apos; must be instatiated.
        '''</summary>
        Friend ReadOnly Property PermissionsMemberNullExceptionMessage() As String
            Get
                Return ResourceManager.GetString("PermissionsMemberNullExceptionMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;permissions&apos; must be instantiated.
        '''</summary>
        Friend ReadOnly Property PermissionsPermissionsNullExceptionMessage() As String
            Get
                Return ResourceManager.GetString("PermissionsPermissionsNullExceptionMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ses00053.
        '''</summary>
        Friend ReadOnly Property PermissionTeamLeaderID() As String
            Get
                Return ResourceManager.GetString("PermissionTeamLeaderID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ses00055.
        '''</summary>
        Friend ReadOnly Property PermissionUnitMemberID() As String
            Get
                Return ResourceManager.GetString("PermissionUnitMemberID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Members.
        '''</summary>
        Friend ReadOnly Property SettingsAllMembers() As String
            Get
                Return ResourceManager.GetString("SettingsAllMembers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Members.
        '''</summary>
        Friend ReadOnly Property SettingsCurrentMembers() As String
            Get
                Return ResourceManager.GetString("SettingsCurrentMembers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm that you want to permanently delete {0} {1} from the database?.
        '''</summary>
        Friend ReadOnly Property SettingsDeleteMemberCaption() As String
            Get
                Return ResourceManager.GetString("SettingsDeleteMemberCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Member Deletion.
        '''</summary>
        Friend ReadOnly Property SettingsDeleteMemberTitle() As String
            Get
                Return ResourceManager.GetString("SettingsDeleteMemberTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Privledges:.
        '''</summary>
        Friend ReadOnly Property SettingsPrivledgesDefaultText() As String
            Get
                Return ResourceManager.GetString("SettingsPrivledgesDefaultText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}&apos;s privledges:.
        '''</summary>
        Friend ReadOnly Property SettingsPrivledgesPersonalText() As String
            Get
                Return ResourceManager.GetString("SettingsPrivledgesPersonalText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resigned Members.
        '''</summary>
        Friend ReadOnly Property SettingsResignedMembers() As String
            Get
                Return ResourceManager.GetString("SettingsResignedMembers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Member.
        '''</summary>
        Friend ReadOnly Property SettingsUpdateMemberTitle() As String
            Get
                Return ResourceManager.GetString("SettingsUpdateMemberTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @members.ses.vic.gov.au.
        '''</summary>
        Friend ReadOnly Property StandardEmailEnding() As String
            Get
                Return ResourceManager.GetString("StandardEmailEnding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Idle..
        '''</summary>
        Friend ReadOnly Property StatusLabelIdleText() As String
            Get
                Return ResourceManager.GetString("StatusLabelIdleText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating database.
        '''</summary>
        Friend ReadOnly Property StatusLabelUpdatingDatabase() As String
            Get
                Return ResourceManager.GetString("StatusLabelUpdatingDatabase", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
